name: hassfest Validation

on:
  push:
  pull_request:
  schedule:
    - cron: 0 2 * * *

jobs:
  validate:
    name: HASS Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
