name: hassfest Validation

on:
  push:
  pull_request:

jobs:
  validate:
    name: HASS Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"
